name: Code Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Base Dependencies
      run: python -m pip install -e .
    - name: Install Testing Dependencies
      run: make install
    - name: Prep CI tests
      run: |
        mkdir ~/.cache
        mkdir ~/.cache/bpemb
        mkdir ~/.cache/bpemb/en
        mv tests/data/en.wiki.bpe.vs1000.d25.w2v.bin ~/.cache/bpemb/en
        mv tests/data/en.wiki.bpe.vs1000.model ~/.cache/bpemb/en
    - name: Interrogate
      if: always()
      run: make interrogate
    - name: Black
      if: always()
      run: black -t py37 --check embetter tests setup.py
    - name: Flake8
      if: always()
      run: make flake
    - name: Unittest
      if: always()
      run: make test
